#!/usr/bin/env perl

use strict;
use warnings;

package t0;

use Path::Dispatcher::Declarative -base;

on qr#/# => sub { print "/\n" };

on '/apple' => sub { print "apple\n" };

on qr#pl# => sub { print "pl\n" };

package main;

t0->run( "/apple" );

my $dispatch = t0->dispatch( "/apple" );

warn join "\n", $dispatch->matches;

